### PR TITLE
Update to v0.11.15 and add missing x86_64-unknown-uefi target 

### LINKED ISSUE #556: Basic examples fails when updated to v0.11.15
`x86_64-unknown-uefi`-target is missing

```
  [lock_api 0.4.10] error[E0463]: can't find crate for `std`
  [lock_api 0.4.10]   |
  [lock_api 0.4.10]   = note: the `x86_64-unknown-uefi` target may not be installed
  [lock_api 0.4.10]   = help: consider downloading the target with `rustup target add x86_64-unknown-uefi`
  [lock_api 0.4.10]   = help: consider building the standard library from source with `cargo build -Zbuild-std`
  [lock_api 0.4.10] 
  [lock_api 0.4.10] error: aborting due to 1 previous error
  [lock_api 0.4.10] 
  [lock_api 0.4.10] For more information about this error, try `rustc --explain E0463`.
     Compiling rustc_version v0.4.0
       Running `CARGO=/home/pepper/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=rustc_version CARGO_MANIFEST_DIR=/home/pepper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc_version-0.4.0 CARGO_MANIFEST_PATH=/home/pepper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc_version-0.4.0/Cargo.toml CARGO_PKG_AUTHORS='Dirkjan Ochtman <dirkjan@ochtman.nl>:Marvin Löbel <loebel.marvin@gmail.com>' CARGO_PKG_DESCRIPTION='A library for querying the version of a installed rustc compiler' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT/Apache-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=rustc_version CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='https://github.com/Kimundi/rustc-version-rs' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.4.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=4 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/tmp/cargo-installpqEK6z/release/deps:/home/pepper/dev/ghrepos/bootloader/examples/basic/target/debug/deps:/home/pepper/dev/ghrepos/bootloader/examples/basic/target/debug:/home/pepper/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/pepper/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' /home/pepper/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name rustc_version --edition=2018 /home/pepper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc_version-0.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=22f0e4f99d384568 -C extra-filename=-0da39d057b49ccfc --out-dir /tmp/cargo-installpqEK6z/release/deps -C strip=debuginfo -L dependency=/tmp/cargo-installpqEK6z/release/deps --extern semver=/tmp/cargo-installpqEK6z/release/deps/libsemver-abfdaa925a6a7723.rmeta --cap-lints warn`
  [lock_api 0.4.10] error[E0463]: can't find crate for `core`
  [lock_api 0.4.10]   |
  [lock_api 0.4.10]   = note: the `x86_64-unknown-uefi` target may not be installed
  [lock_api 0.4.10]   = help: consider downloading the target with `rustup target add x86_64-unknown-uefi`
  [lock_api 0.4.10]   = help: consider building the standard library from source with `cargo build -Zbuild-std`
  [lock_api 0.4.10] 
  [lock_api 0.4.10] error: aborting due to 1 previous error
  [lock_api 0.4.10] 
  [lock_api 0.4.10] For more information about this error, try `rustc --explain E0463`.
```

### PR DESCRIPTION
**Pull request by peppergrayxyz**
Update dependencies and fix a regression (#556)

### CODE REVIEW

**Review by Freax13 — APPROVED** [review]
Thank you for your contribution!

LGTM :shipit:
